src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The venue this prototype campaign can be used for</description>
        <label>Venue</label>
        <referenceTo>PatronTicket__Venue__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/PatronTicket__EventInstance__c.object
<CustomObject>
</CustomObject>

src/classes/eiInstance.cls
public class eiInstance {
	public PatronTicket__EventInstance__c eventInstance {get;set;}
	public String campaign {get;set;}
	public Boolean build {get;set;}
	public List<SelectOption> options {get; set;}
	public eiInstance(PatronTicket__EventInstance__c ei) {
		eventInstance = ei;
		options = new List<SelectOption>();
		List<Campaign> prototypes = [SELECT Id,Name 
									 FROM Campaign 
									 WHERE Venue__c = :eventInstance.PatronTicket__Venue__c];
		for(Integer i = 0; i < prototypes.size(); i++) {
			SelectOption option = new SelectOption(prototypes[i].Id,prototypes[i].Name);
			options.add(option);
		}
	}
}